repos:
  - repo: local
    hooks:
      - id: fmt-kernel
        name: fmt (kernel)
        entry: bash -c 'cd kernel && cargo fmt --check'
        language: system
        files: '^kernel/.*\.rs$'
        pass_filenames: false

      - id: fmt-libc
        name: fmt (libc)
        entry: bash -c 'cd libc && cargo fmt --check'
        language: system
        files: '^libc/.*\.rs$'
        pass_filenames: false

      - id: fmt-mono
        name: fmt (mono)
        entry: bash -c 'cd mono && cargo fmt --check'
        language: system
        files: '^mono/.*\.rs$'
        pass_filenames: false

  - repo: https://github.com/bnjbvr/cargo-machete
    rev: v0.9.1
    hooks:
      - id: cargo-machete

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        files: '.*\.rs$'
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - /*| *| */

        
