repos:
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: clippy

  - repo: https://github.com/bnjbvr/cargo-machete
    rev: v0.9.1
    hooks:
      - id: cargo-machete

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        files: '.*\.rs$'
        args:
          - --license-filepath
          - LICENSE
          - --comment-style
          - /*| *| */

        
