/*
 * ISC License
 *
 * Copyright (c) 2025-2026 xjunko
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */

pub const PAGE_SIZE: usize = 4096;

pub const KERNEL_STACK_SIZE: usize = PAGE_SIZE;
pub const PROCESS_STACK_SIZE: usize = PAGE_SIZE * 4;

pub const KERNEL_HEAP_START: usize = 0xFFFF_9000_0000_0000;
pub const KERNEL_HEAP_SIZE: usize = 1024 * 1024;

pub const USER_STACK_TOP_PAGE: u64 = 0x0000_0000_7FFF_F000;
pub const USER_STACK_PAGES: u64 = 256; // 1mb stack
pub const USER_STACK_INITIAL_SLACK: u64 = 0x100;

pub const USER_DYNAMIC_LINKER_BASE: u64 = (USER_STACK_TOP_PAGE)
    - (USER_STACK_PAGES * PAGE_SIZE as u64)
    - (USER_STACK_INITIAL_SLACK);
